name: dCFE
channels:
  - pytorch
  - defaults
  # - anaconda
  - conda-forge
dependencies:
  - bmipy
  - bokeh
  - cpuonly
  - jupyter
  - matplotlib
  - netcdf4
  - pandas
  - ruamel.yaml
  - torchdiffeq
  - tqdm
  - pip
  - pip:
    - hydra-core