defaults:
  - _self_
  - data: \config\test
  - models: \config\base

cwd: G:\Shared drives\SI_NextGen_Aridity\dCFE\
save_name: debugger
output_dir: ${cwd}\output\
device: cpu
num_processes: 1

run_type: ML_synthetic_test # Choose between "generate_synthetic" & "ML" & "ML_synthetic_test"
soil_scheme: ode # ode # classic
basin_id: '01137500'

synthetic:
  output_dir: ${cwd}\data\synthetic_case\
  nams: ${basin_id}_synthetic_${soil_scheme}.csv
  param_nams: ${basin_id}_synthetic_params_${soil_scheme}
  refkdt: 3
  satdk: 0.00001

conversions:
  cm_to_mm: 10.0
  mm_to_cm: 0.1
  cm_to_m: 0.01
  m_to_mm: 1000
  hr_to_sec: 3600.0

################## HYDRA CONFIG #######################
hydra:
  help:
    app_name: dCFE
    header: == ${hydra.help.app_name} ==
    template: |-
      ${hydra.help.header}

      This is ${hydra.help.app_name}!
      Work in progress

      ${hydra.help.footer}
    footer: |-
      Powered by Hydra (https:\\hydra.cc)
      Use --hydra-help to view Hydra specific help
  job:
    name: ${save_name}
  run:
    dir: ${cwd}\output\\${now:%Y-%m-%d}_${hydra.job.name} #\${now:%H-%M-%S}