hyperparameters:
  epochs: 3 #1000 #50
  learning_rate: 1e-03 #0.1 # 0.001
  warmup: 500
  step_size: 1
  gamma: 0.7

mlp:
  hidden_size: 6
  # input_size: 2
  num_attrs: 3
  # output_size: 2
  num_params: 2
  num_states: 2

transformation:
  refkdt: # refkdt range taking from https://www.sciencedirect.com/science/article/pii/S0022169420303620
  - 0.5
  - 5
  satdk:
  - 0
  - 0.000726