hyperparameters:
  epochs: 1 #50
  learning_rate: 0.1 # 0.001
  warmup: 100

mlp:
  hidden_size: 6
  input_size: 4
  output_size: 2

transformation:
  refkdt: # https://www.sciencedirect.com/science/article/pii/S0022169420303620
  - 0.5
  - 5
  satdk:
  - 0
  - 0.000726